version: '3.9'

services:
  app01:
    image: gabriel1101/backend-challange:1.0
    hostname: app01
    ports:
     - 8081:8080
    environment:
     - DB_USER=java
     - DB_PASSWORD=java@123
     - DB_JDBC_URL=jdbc:postgresql://db_challange_bck:5432/challange_backend_db
  app02:
    image: gabriel1101/backend-challange:1.0
    hostname: app02
    ports:
     - 8082:8080
    environment:
     - DB_USER=java
     - DB_PASSWORD=java@123
     - DB_JDBC_URL=jdbc:postgresql://db_challange_bck:5432/challange_backend_db
  db:
    image: postgres:16.2
    hostname: db_challange_bck
    environment:
      - POSTGRES_PASSWORD=java@123
      - POSTGRES_USER=java
      - POSTGRES_DB=challange_backend_db
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app01
      - app02
    ports:
        # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999"